language: shell
dist: xenial
os: linux
before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple
script:
  - bash scripts/sync-img.sh
services:
  - docker
before_install:
  - sudo apt-get install jq
  - chmod +x scripts/sync-img.sh
